#!/usr/bin/env bash
# Sync the vendored AppRouter.d.ts from the backend repo.
#
# Run after any backend tRPC API change (new procedure, changed input/output).
# The bundled .d.ts lives in Sebdysart/hustlexp-ai-backend at
# dist-types/AppRouter.d.ts and is regenerated by `npm run emit:trpc-types`
# on the backend side.
#
# Requires `gh` authenticated against Sebdysart/hustlexp-ai-backend.

set -euo pipefail

REPO="${HUSTLEXP_BACKEND_REPO:-Sebdysart/hustlexp-ai-backend}"
REF="${HUSTLEXP_BACKEND_REF:-claude/audit-backend-workflow-mFb7a}"
SRC_PATH="dist-types/AppRouter.d.ts"
DEST_PATH="types/trpc/AppRouter.d.ts"

cd "$(dirname "$0")/.."

mkdir -p "$(dirname "$DEST_PATH")"

echo "Fetching $REPO@$REF:$SRC_PATH ..."
gh api "repos/$REPO/contents/$SRC_PATH?ref=$REF" \
  -H "Accept: application/vnd.github.raw" \
  > "$DEST_PATH"

LINES=$(wc -l < "$DEST_PATH" | tr -d ' ')
if ! grep -q "export type AppRouter" "$DEST_PATH"; then
  echo "FATAL: vendored file does not export AppRouter" >&2
  exit 1
fi
echo "Wrote $DEST_PATH ($LINES lines)"
