#!/usr/bin/env bash
# Sync the vendored AppRouter.d.ts from the backend repo.
#
# Run after any backend tRPC API change (new procedure, changed input/output).
# The bundled .d.ts lives in Sebdysart/hustlexp-ai-backend at
# dist-types/AppRouter.d.ts and is regenerated by `npm run emit:trpc-types`
# on the backend side.
#
# Source-of-truth resolution (first that works wins):
#   1. Local backend checkout — set HUSTLEXP_BACKEND_DIR to the backend repo
#      root. Preferred: reflects on-machine backend including UNPUSHED work.
#   2. GitHub (fallback) — fetched via `gh` from $REPO@$REF. Sees only
#      COMMITTED+PUSHED backend state.
#
# Safety guard: the script writes to a temp file, validates it exports
# AppRouter, and REFUSES to overwrite the current vendored copy with a file
# that has FEWER lines (a likely regression — e.g. pulling a stale GitHub copy
# while the backend has unpushed type changes) unless --force is passed.
#
# Usage:
#   ./scripts/sync-trpc-types.sh                         # sync (guarded)
#   HUSTLEXP_BACKEND_DIR=/path/to/backend ./scripts/sync-trpc-types.sh
#   ./scripts/sync-trpc-types.sh --force                 # allow shrinking

set -euo pipefail

FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

REPO="${HUSTLEXP_BACKEND_REPO:-Sebdysart/hustlexp-ai-backend}"
REF="${HUSTLEXP_BACKEND_REF:-claude/audit-backend-workflow-mFb7a}"
SRC_PATH="dist-types/AppRouter.d.ts"
DEST_PATH="types/trpc/AppRouter.d.ts"

cd "$(dirname "$0")/.."
mkdir -p "$(dirname "$DEST_PATH")"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

if [[ -n "${HUSTLEXP_BACKEND_DIR:-}" && -f "$HUSTLEXP_BACKEND_DIR/$SRC_PATH" ]]; then
  cp "$HUSTLEXP_BACKEND_DIR/$SRC_PATH" "$TMP"
  echo "Source: local backend checkout $HUSTLEXP_BACKEND_DIR/$SRC_PATH"
else
  echo "Fetching $REPO@$REF:$SRC_PATH (committed+pushed state only) ..."
  gh api "repos/$REPO/contents/$SRC_PATH?ref=$REF" \
    -H "Accept: application/vnd.github.raw" > "$TMP"
fi

if ! grep -q "export type AppRouter" "$TMP"; then
  echo "FATAL: fetched file does not export AppRouter — refusing to write." >&2
  exit 1
fi

NEW_LINES=$(wc -l < "$TMP" | tr -d ' ')
OLD_LINES=0
[[ -f "$DEST_PATH" ]] && OLD_LINES=$(wc -l < "$DEST_PATH" | tr -d ' ')

if [[ "$FORCE" -eq 0 && "$NEW_LINES" -lt "$OLD_LINES" ]]; then
  echo "REFUSING: incoming file ($NEW_LINES lines) is SHORTER than current vendored" >&2
  echo "          copy ($OLD_LINES lines) — likely a stale/regressed source." >&2
  echo "          Confirm the backend types are pushed to $REF, or sync from a" >&2
  echo "          local checkout (HUSTLEXP_BACKEND_DIR), or pass --force." >&2
  exit 1
fi

mv "$TMP" "$DEST_PATH"
echo "Wrote $DEST_PATH ($NEW_LINES lines; was $OLD_LINES)"
